apiVersion: v1
kind: Service
metadata:
  name: my-example-nodeport
spec:
  type: NodePort
  selector:
    app.kubernetes.io/instance: my-example # label of the pod
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30031